name: storypad
description: Minimalist application to write stories, notes, diary!
publish_to: "none"
version: 2.0.1+226

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  copy_with_extension: ^6.0.0
  provider: ^6.1.2
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.5
  html_character_entities: ^1.0.0+1
  flutter_quill: ^11.0.0-dev.21
  animations: ^2.0.11
  dynamic_color: ^1.7.0
  animated_clipper: ^0.2.0+2
  shared_preferences: ^2.3.4
  google_fonts: ^6.2.1
  fuzzy: ^0.5.1
  adaptive_dialog: ^2.4.0
  flutter_slidable: ^3.1.2
  local_auth: ^2.3.0
  flutter_markdown: ^0.7.4+3
  lottie: ^3.3.0
  confetti: ^0.8.0
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  firebase_analytics: ^11.4.1
  firebase_crashlytics: ^4.3.1
  firebase_remote_config: ^5.3.1
  googleapis: ^13.2.0
  device_info_plus: ^11.2.0
  cached_network_image: ^3.4.1
  flutter_custom_tabs: ^2.1.0
  photo_view: ^0.15.0
  dismissible_page: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  sqflite: ^2.4.1
  in_app_review: ^2.0.10
  package_info_plus: ^8.1.3
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  copy_with_extension_gen: ^6.0.0
  objectbox_generator: any
  flutter_gen_runner: ^5.8.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/emoji-64/
